/**
 * `features/posts` — mirrors the backend package `com.socialapp.posts` (PostController,
 * LocationController, QuizController, CommentController, PostReactionController and
 * EventController: 22 endpoints). One module, one barrel; the checkpoint schedule splits
 * into three cycles but the folder never does (CLAUDE.md §4).
 *
 * Cycle 1 (P2.4a) — core: post CRUD + accept-answer, location resolution, quiz submit.
 * Cycle 2 (P2.4′) — comments + reactions. Cycle 3 (P2.4″) — events.
 *
 * `EventController` answers on `/v1/api/events`, which looks like it should be its own
 * feature and must not become one: the path is the exception, the package is the rule
 * (CLAUDE.md §4). An event is a post of type EVENT, and every event endpoint refuses a
 * postId that is not one.
 *
 * NOTE: this domain is **write-only**. There is no `GET /posts` and no `GET /posts/{id}` —
 * posts are read through `newsfeed` and `search`, which embed the post payload.
 */

export { postsApi, locationApi, quizApi, commentsApi, reactionsApi, eventsApi } from './api';

export {
  PostComposer,
  type PostComposerProps,
  LocationPicker,
  type LocationPickerProps,
  LocationBadge,
  locationLabel,
  type LocationBadgeProps,
  CodeSnippetFields,
  type CodeSnippetFieldsProps,
  ArticleFields,
  type ArticleFieldsProps,
  QnaFields,
  PollFields,
  POLL_MIN_OPTIONS,
  type PollFieldsProps,
  LinkFields,
  isValidLinkUrl,
  type LinkFieldsProps,
  EventFields,
  type EventFieldsProps,
  PostCard,
  PostImages,
  type PostImagesProps,
  type PostCardProps,
  type PostCardAuthor,
  CodeSnippetBody,
  type CodeSnippetBodyProps,
  ArticleBody,
  type ArticleBodyProps,
  LinkBody,
  type LinkBodyProps,
  QnaBody,
  type QnaBodyProps,
  PollBody,
  type PollBodyProps,
  BookBody,
  type BookBodyProps,
  type BookBodySummary,
  EventBody,
  type EventBodyProps,
  EventRsvpBar,
  type EventRsvpBarProps,
  EventAttendeeList,
  type EventAttendeeListProps,
  EventCalendarActions,
  type EventCalendarActionsProps,
  ReactionBar,
  type ReactionBarProps,
  ACTION_GLYPH_BUTTON,
  ACTION_GLYPH,
  ACTION_GROUP,
  ACTION_COUNT,
  CommentPreview,
  CommentThread,
  type CommentThreadProps,
  CommentItem,
  type CommentItemProps,
  CommentComposer,
  type CommentComposerProps,
  QuizTaker,
  type QuizTakerProps,
  PostEditor,
  type PostEditorProps,
  type PostEditorState,
  PostMenu,
  type PostMenuProps,
} from './components';

export {
  postKeys,
  useCreatePost,
  useCreateBookPost,
  useUpdatePost,
  useDeletePost,
  useAcceptAnswer,
  useUnacceptAnswer,
  useResolveLocation,
  useSubmitQuiz,
  useComments,
  useCreateComment,
  useUpdateComment,
  useDeleteComment,
  useUpsertCommentReaction,
  useRemoveCommentReaction,
  groupComments,
  useMyReaction,
  useUpsertReaction,
  useRemoveReaction,
  useAttendees,
  useAttendeeCount,
  useRsvp,
  useAddToGoogleCalendar,
  useCalendarStatus,
  useGoogleAuthUrl,
  useExportIcs,
  findMyRsvp,
  type PostMutationOptions,
  type CreateBookPostVariables,
  type UpdatePostVariables,
  type AcceptAnswerVariables,
  type SubmitQuizVariables,
  type CommentWithReplies,
  type CreateCommentVariables,
  type UpdateCommentVariables,
  type DeleteCommentVariables,
  type CommentReactionOptions,
  type CommentReactionVariables,
  type UpsertCommentReactionVariables,
  type ReactionMutationOptions,
  type UpsertReactionVariables,
  type RsvpVariables,
} from './hooks';

export type {
  PostType,
  PostVisibility,
  LocationType,
  LocationDetails,
  EventDetails,
  CodeSnippetDetails,
  ArticleDetails,
  QnaDetails,
  PollDetails,
  LinkDetails,
  QuizQuestion,
  QuizDetails,
  PublicQuizDetails,
  CreateBookRequest,
  CreatePostRequest,
  UpdatePostRequest,
  LocationResolutionRequest,
  LocationResolution,
  SubmitQuizRequest,
  QuizResult,
  PostComment,
  CreateCommentRequest,
  UpdateCommentRequest,
  ReactionType,
  MyReaction,
  UpsertReactionRequest,
  RsvpStatus,
  EventAttendee,
  AttendeeCount,
  GoogleAuthUrl,
  CalendarStatus,
} from './types';
